---
#
# List of collections used by the guest-setup tests
#
collections:
  - name: community.postgresql
    version: 4.1.0
  # Newer versions require Ansible 2.17+
  - name: community.crypto
    version: 2.26.6
  # Newer versions require Ansible 2.17+
  - name: community.general
    version: 11.4.1
  # Version 1.6+ breaks standard-test-roles
  # Unsupported parameters for (ansible.posix.synchronize) module: ssh_args
  - name: ansible.posix
    version: 1.5.4
